# Environment for Alice TRF analysis
# usage: $ conda env create --file=environment.yml
name: eelbrain
channels:
- conda-forge
dependencies:
- eelbrain >= 0.39.2
- pip
- ipython
- jupyter
- ipywidgets
- jupytext
- seaborn
- pip:
  - https://github.com/christianbrodbeck/gammatone/archive/fmax.zip
  - https://github.com/Hugo-W/pyEEG/archive/refs/heads/master.zip
